In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [57]:
data=pd.read_csv("Ads.csv")
data.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [58]:
real_x=data.iloc[:,[2,3]].values
real_y=data.iloc[:,4].values

In [59]:
training_x,test_x,training_y,test_y = train_test_split(real_x,real_y,test_size=0.25,random_state=0)

In [60]:
sc=StandardScaler()
testing_x=sc.fit_transform(training_x)
test_x = sc.transform(test_x)
test_x



array([[ 2.10286908, -1.07926599],
       [-0.16568602, -0.44391519],
       [-0.56601928, -0.84518938],
       [-0.56601928, -1.5139797 ],
       [ 0.63498049, -0.44391519],
       [ 0.36809165, -0.57767325],
       [-0.43257486, -0.07608051],
       [-1.5001302 , -1.17958454],
       [-1.36668578,  0.86022594],
       [ 0.23464723,  1.32837917],
       [-0.69946369,  0.89366546],
       [ 1.43564699, -0.31015712],
       [ 0.36809165,  0.29175417],
       [-0.83290811,  0.96054449],
       [-0.0322416 ,  0.65958885],
       [ 0.23464723,  3.00035498],
       [-0.29913044, -0.54423374],
       [-0.56601928,  0.79334691],
       [-0.0322416 , -0.37703616],
       [ 0.23464723, -1.41366116],
       [ 0.23464723,  2.49876223],
       [ 0.50153607, -1.17958454],
       [-0.96635253, -1.34678212],
       [-0.56601928, -1.01238696],
       [-0.43257486, -1.34678212],
       [ 1.30220258,  0.49239126],
       [-0.83290811, -1.24646357],
       [ 0.36809165, -0.00920148],
       [-0.29913044,

In [61]:
classifer_LR=LogisticRegression(random_state=0)
classifer_LR.fit(training_x,training_y)

c:\users\bibhuti\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [62]:
y_pred=classifer_LR.predict(test_x)

In [63]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int64)

In [64]:
test_y

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0], dtype=int64)

In [65]:
c_m=confusion_matrix(test_y,y_pred)
c_m

array([[38,  0],
       [12,  0]], dtype=int64)

In [66]:
from matplotlib.colors import ListedColormap

In [ ]:
X_set, y_set = training_x, training_y
X1, X2 = np.meshgrid(np.arange(start = X_set[:,0].min()-1,stop = X_set[:,0].max()+1, step = 0.1),
         np.arange(start = X_set[:,1].min()-1, stop = X_set[:,1].max()+1, step = 0.1))

plt.contourf(X1, X2, classifer_LR.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i,j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set==j,0],X_set[y_set==j,1],c=ListedColormap(("red","green"))(i),label=j)
plt.title("Logistic Regression(Training set)")
plt.xabel("Age")
plt.ylabel("Estimated Salary")
plt.legend()
plt.show()